services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_ui.py
    plan: starter
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DB_PATH
        value: /var/data/bot.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
